[2020-03-17T08:23:44.973] [INFO] app - API_OBJECT_UNDEFINED:object=requirements
[2020-03-17T08:23:54.410] [INFO] app - API_OBJECT_UNDEFINED:object=requirements
[2020-03-17T08:27:28.509] [INFO] app - API_OBJECT_UNDEFINED:object=requirements
[2020-03-17T08:27:28.532] [INFO] app - API_OBJECT_UNDEFINED:object=requirements
[2020-03-17T08:27:34.905] [INFO] app - API_OBJECT_UNDEFINED:object=requirements
[2020-03-17T08:27:34.913] [INFO] app - API_OBJECT_UNDEFINED:object=requirements
[2020-03-17T08:33:12.231] [INFO] app - API_OBJECT_UNDEFINED:object=requirements
[2020-03-17T08:33:12.241] [INFO] app - API_OBJECT_UNDEFINED:object=requirements
[2020-03-17T08:33:43.338] [INFO] app - API_OBJECT_UNDEFINED:object=bugreports
[2020-03-17T08:33:43.362] [INFO] app - API_OBJECT_UNDEFINED:object=bugreports
[2020-03-17T08:33:50.058] [INFO] app - API_OBJECT_UNDEFINED:object=requirements
[2020-03-17T08:33:50.067] [INFO] app - API_OBJECT_UNDEFINED:object=requirements
[2020-03-17T08:33:54.723] [INFO] app - API_OBJECT_UNDEFINED:object=requirements
[2020-03-17T08:34:07.295] [INFO] app - API_OBJECT_UNDEFINED:object=requirements
[2020-03-17T08:35:29.418] [INFO] app - API_OBJECT_UNDEFINED:object=requirements
[2020-03-17T08:35:29.429] [INFO] app - API_OBJECT_UNDEFINED:object=requirements
[2020-03-17T08:35:41.102] [INFO] app - API_OBJECT_UNDEFINED:object=requirements
[2020-03-17T08:36:21.021] [INFO] app - API_OBJECT_UNDEFINED:object=bugreports
[2020-03-17T08:36:21.029] [INFO] app - API_OBJECT_UNDEFINED:object=bugreports
[2020-03-17T08:36:26.221] [INFO] app - API_OBJECT_UNDEFINED:object=bugreports
[2020-03-17T08:36:26.245] [INFO] app - API_OBJECT_UNDEFINED:object=bugreports
[2020-03-17T09:35:49.863] [INFO] app - *** SYSTEM STARTUP on PORT (5858) ***
[2020-03-17T09:38:07.708] [INFO] app - *** SYSTEM STARTUP on PORT (5858) ***
[2020-03-17T09:38:34.001] [ERROR] app - { Error: ER_BAD_FIELD_ERROR: Unknown column 'type' in 'field list'
    at Query.Sequence._packetToError (D:\able_project\CloudServer\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (D:\able_project\CloudServer\node_modules\mysql\lib\protocol\sequences\Query.js:77:18)
    at Protocol._parsePacket (D:\able_project\CloudServer\node_modules\mysql\lib\protocol\Protocol.js:278:23)
    at Parser.write (D:\able_project\CloudServer\node_modules\mysql\lib\protocol\Parser.js:76:12)
    at Protocol.write (D:\able_project\CloudServer\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (D:\able_project\CloudServer\node_modules\mysql\lib\Connection.js:91:28)
    at Socket.<anonymous> (D:\able_project\CloudServer\node_modules\mysql\lib\Connection.js:502:10)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
    at Protocol._enqueue (D:\able_project\CloudServer\node_modules\mysql\lib\protocol\Protocol.js:144:48)
    at Connection.query (D:\able_project\CloudServer\node_modules\mysql\lib\Connection.js:200:25)
    at D:\able_project\CloudServer\node_modules\knex\lib\dialects\mysql\index.js:152:18
From previous event:
    at Client_MySQL._query (D:\able_project\CloudServer\node_modules\knex\lib\dialects\mysql\index.js:146:12)
    at Client_MySQL.query (D:\able_project\CloudServer\node_modules\knex\lib\client.js:197:17)
    at Runner.<anonymous> (D:\able_project\CloudServer\node_modules\knex\lib\runner.js:146:36)
From previous event:
    at D:\able_project\CloudServer\node_modules\knex\lib\runner.js:65:21
    at runCallback (timers.js:694:18)
    at tryOnImmediate (timers.js:665:5)
    at processImmediate (timers.js:647:5)
From previous event:
    at Runner.run (D:\able_project\CloudServer\node_modules\knex\lib\runner.js:51:31)
    at Builder.Target.then (D:\able_project\CloudServer\node_modules\knex\lib\interface.js:35:43)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sqlMessage: 'Unknown column \'type\' in \'field list\'',
  sqlState: '42S22',
  index: 0,
  sql:
   'select `id`, `name`, `type`, `inputor`, `updator`, `updateTime`, `state` from `order` where `stype` = \'requirement\'' }
[2020-03-17T09:38:43.622] [INFO] app - *** SYSTEM STARTUP on PORT (5858) ***
[2020-03-17T09:39:12.441] [INFO] app - *** SYSTEM STARTUP on PORT (5858) ***
[2020-03-17T09:39:17.232] [ERROR] app - TypeError: Cannot read property 'id' of undefined
    at Object.Patch (D:\able_project\CloudServer\models\kernel.js:193:47)
    at RestfulAPIMethods.(anonymous function) (D:\able_project\CloudServer\routes\restful.js:32:60)
    at dispatch (D:\able_project\CloudServer\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at next (D:\able_project\CloudServer\node_modules\koa-router\node_modules\koa-compose\index.js:45:18)
    at module.exports (D:\able_project\CloudServer\middlewares\authRouter.js:13:10)
    at dispatch (D:\able_project\CloudServer\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at next (D:\able_project\CloudServer\node_modules\koa-router\node_modules\koa-compose\index.js:45:18)
    at D:\able_project\CloudServer\node_modules\koa-router\lib\router.js:346:16
    at dispatch (D:\able_project\CloudServer\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at next (D:\able_project\CloudServer\node_modules\koa-router\node_modules\koa-compose\index.js:45:18)
    at route.use (D:\able_project\CloudServer\routes\restful.js:97:19)
    at dispatch (D:\able_project\CloudServer\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at next (D:\able_project\CloudServer\node_modules\koa-router\node_modules\koa-compose\index.js:45:18)
    at D:\able_project\CloudServer\node_modules\koa-router\lib\router.js:346:16
    at dispatch (D:\able_project\CloudServer\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at D:\able_project\CloudServer\node_modules\koa-router\node_modules\koa-compose\index.js:36:12
    at dispatch (D:\able_project\CloudServer\node_modules\koa-router\lib\router.js:351:31)
    at dispatch (D:\able_project\CloudServer\node_modules\koa-compose\index.js:42:32)
    at module.exports (D:\able_project\CloudServer\middlewares\auth.js:50:9)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[2020-03-17T09:39:57.186] [INFO] app - *** SYSTEM STARTUP on PORT (5858) ***
[2020-03-17T09:40:00.621] [INFO] app - *** SYSTEM STARTUP on PORT (5858) ***
[2020-03-17T09:40:09.552] [INFO] app - *** SYSTEM STARTUP on PORT (5858) ***
[2020-03-17T09:43:06.188] [INFO] app - *** SYSTEM STARTUP on PORT (5858) ***
[2020-03-17T10:12:36.937] [ERROR] app - ReferenceError: now is not defined
    at Object.Patch (D:\able_project\CloudServer\models\kernel.js:204:24)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[2020-03-17T10:13:31.390] [INFO] app - *** SYSTEM STARTUP on PORT (5858) ***
[2020-03-17T10:27:09.422] [INFO] app - *** SYSTEM STARTUP on PORT (5858) ***
[2020-03-17T10:27:13.565] [ERROR] app - ReferenceError: autosign is not defined
    at Object.Post (D:\able_project\CloudServer\models\kernel.js:163:9)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[2020-03-17T10:27:30.973] [INFO] app - *** SYSTEM STARTUP on PORT (5858) ***
[2020-03-17T10:27:32.257] [ERROR] app - ReferenceError: DataTransferItem is not defined
    at Object.Post (D:\able_project\CloudServer\models\kernel.js:165:20)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[2020-03-17T10:27:44.837] [INFO] app - *** SYSTEM STARTUP on PORT (5858) ***
[2020-03-17T10:29:15.702] [INFO] app - *** SYSTEM STARTUP on PORT (5858) ***
[2020-03-17T10:49:52.273] [INFO] app - *** SYSTEM STARTUP on PORT (5858) ***
[2020-03-17T16:19:54.530] [INFO] app - *** SYSTEM STARTUP on PORT (5858) ***
[2020-03-17T16:20:39.044] [INFO] app - *** SYSTEM STARTUP on PORT (5858) ***
[2020-03-17T16:44:19.766] [INFO] app - *** SYSTEM STARTUP on PORT (5858) ***
[2020-03-17T16:45:45.818] [INFO] app - *** SYSTEM STARTUP on PORT (5858) ***
