[2020-07-13T06:29:05.774] [ERROR] app - 登录已过期
[2020-07-13T06:29:16.494] [ERROR] app - 登录已过期
[2020-07-13T06:29:20.788] [ERROR] app - TypeError: ctx.userlog.info is not a function
    at Object.out.Post (C:\Users\BIM02\Desktop\ServerKT\restful\v0\sessions.js:102:22)
[2020-07-13T06:30:30.376] [ERROR] app - TypeError: Cannot read property 'name' of undefined
    at Object.app.context.userlog (C:\Users\BIM02\Desktop\ServerKT\app.js:18:60)
    at Object.out.Post (C:\Users\BIM02\Desktop\ServerKT\restful\v0\sessions.js:102:14)
[2020-07-13T06:31:53.113] [ERROR] app - { Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'from `user` left join `dep_user` on `dep_user`.`user_id` = `user`.`id` left join' at line 1
    at Query.Sequence._packetToError (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
    --------------------
    at Protocol._enqueue (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\protocol\Protocol.js:144:48)
    at Connection.query (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\Connection.js:198:25)
    at C:\Users\BIM02\Desktop\ServerKT\node_modules\knex\lib\dialects\mysql\index.js:135:18
    at new Promise (<anonymous>)
    at Client_MySQL._query (C:\Users\BIM02\Desktop\ServerKT\node_modules\knex\lib\dialects\mysql\index.js:129:12)
    at Client_MySQL.query (C:\Users\BIM02\Desktop\ServerKT\node_modules\knex\lib\client.js:169:17)
    at Runner.query (C:\Users\BIM02\Desktop\ServerKT\node_modules\knex\lib\runner.js:134:36)
    at C:\Users\BIM02\Desktop\ServerKT\node_modules\knex\lib\runner.js:40:23
    at client.acquireConnection.catch.then (C:\Users\BIM02\Desktop\ServerKT\node_modules\knex\lib\runner.js:260:24)
  code: 'ER_PARSE_ERROR',
  errno: 1064,
  sqlMessage:
   'You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \'from `user` left join `dep_user` on `dep_user`.`user_id` = `user`.`id` left join\' at line 1',
  sqlState: '42000',
  index: 0,
  sql:
   'select `user`.*, group_concat(dep_user.dep_id,\',\', group_concat(role_user.role_id,\',\') from `user` left join `dep_user` on `dep_user`.`user_id` = `user`.`id` left join `role_user` on `role_user`.`user_id` = `user`.`id`' }
[2020-07-13T06:35:04.120] [ERROR] app - { Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'seperator ',') as deps, group_concat(role_user.role_id seperator ',') as roles f' at line 1
    at Query.Sequence._packetToError (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
    --------------------
    at Protocol._enqueue (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\protocol\Protocol.js:144:48)
    at Connection.query (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\Connection.js:198:25)
    at C:\Users\BIM02\Desktop\ServerKT\node_modules\knex\lib\dialects\mysql\index.js:135:18
    at new Promise (<anonymous>)
    at Client_MySQL._query (C:\Users\BIM02\Desktop\ServerKT\node_modules\knex\lib\dialects\mysql\index.js:129:12)
    at Client_MySQL.query (C:\Users\BIM02\Desktop\ServerKT\node_modules\knex\lib\client.js:169:17)
    at Runner.query (C:\Users\BIM02\Desktop\ServerKT\node_modules\knex\lib\runner.js:134:36)
    at C:\Users\BIM02\Desktop\ServerKT\node_modules\knex\lib\runner.js:40:23
    at client.acquireConnection.catch.then (C:\Users\BIM02\Desktop\ServerKT\node_modules\knex\lib\runner.js:260:24)
  code: 'ER_PARSE_ERROR',
  errno: 1064,
  sqlMessage:
   'You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \'seperator \',\') as deps, group_concat(role_user.role_id seperator \',\') as roles f\' at line 1',
  sqlState: '42000',
  index: 0,
  sql:
   'select `user`.*, group_concat(dep_user.dep_id seperator \',\') as deps, group_concat(role_user.role_id seperator \',\') as roles from `user` left outer join `dep_user` on `dep_user`.`user_id` = `user`.`id` left outer join `role_user` on `role_user`.`user_id` = `user`.`id`' }
[2020-07-13T07:05:27.015] [ERROR] app - 没有访问权限
[2020-07-13T07:05:27.022] [ERROR] app - 没有访问权限
[2020-07-13T08:46:14.511] [ERROR] app - 没有访问权限
[2020-07-13T08:52:26.619] [ERROR] app - { key: 'phone', error: '电话号码已存在' }
[2020-07-13T08:57:35.814] [ERROR] app - ReferenceError: debug is not defined
    at B.transaction.catch.e (C:\Users\BIM02\Desktop\ServerKT\restful\v0\users.js:89:7)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[2020-07-13T08:57:54.360] [ERROR] app - { key: 'phone', error: '电话号码已存在' }
[2020-07-13T08:58:40.894] [ERROR] app - TypeError: model.toJSON is not a function
    at Object.out.Post (C:\Users\BIM02\Desktop\ServerKT\restful\v0\users.js:110:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[2020-07-13T08:59:00.998] [ERROR] app - TypeError: model.toJSON is not a function
    at Object.out.Post (C:\Users\BIM02\Desktop\ServerKT\restful\v0\users.js:112:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[2020-07-13T09:33:35.601] [ERROR] app - 没有访问权限
[2020-07-13T09:33:35.609] [ERROR] app - 没有访问权限
[2020-07-13T10:02:50.052] [ERROR] app - TypeError: model.toJSON is not a function
    at Object.out.Post (C:\Users\BIM02\Desktop\ServerKT\restful\v0\users.js:112:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[2020-07-13T10:11:21.092] [ERROR] app - TypeError: model.toJSON is not a function
    at Object.out.Post (C:\Users\BIM02\Desktop\ServerKT\restful\v0\users.js:112:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[2020-07-13T10:23:49.010] [ERROR] app - { key: 'phone', error: '电话号码已存在' }
[2020-07-13T10:25:18.220] [ERROR] app - ReferenceError: model is not defined
    at Function.Post (C:\Users\BIM02\Desktop\ServerKT\models\index.js:105:5)
    at Object.out.Post (C:\Users\BIM02\Desktop\ServerKT\restful\v0\users.js:42:28)
    at RestfulAPIMethods.(anonymous function) (C:\Users\BIM02\Desktop\ServerKT\routes\restful.js:32:60)
    at dispatch (C:\Users\BIM02\Desktop\ServerKT\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at next (C:\Users\BIM02\Desktop\ServerKT\node_modules\koa-router\node_modules\koa-compose\index.js:45:18)
    at C:\Users\BIM02\Desktop\ServerKT\node_modules\koa-router\lib\router.js:346:16
    at dispatch (C:\Users\BIM02\Desktop\ServerKT\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at next (C:\Users\BIM02\Desktop\ServerKT\node_modules\koa-router\node_modules\koa-compose\index.js:45:18)
    at route.use (C:\Users\BIM02\Desktop\ServerKT\routes\restful.js:97:19)
    at dispatch (C:\Users\BIM02\Desktop\ServerKT\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at next (C:\Users\BIM02\Desktop\ServerKT\node_modules\koa-router\node_modules\koa-compose\index.js:45:18)
    at C:\Users\BIM02\Desktop\ServerKT\node_modules\koa-router\lib\router.js:346:16
    at dispatch (C:\Users\BIM02\Desktop\ServerKT\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at C:\Users\BIM02\Desktop\ServerKT\node_modules\koa-router\node_modules\koa-compose\index.js:36:12
    at dispatch (C:\Users\BIM02\Desktop\ServerKT\node_modules\koa-router\lib\router.js:351:31)
    at dispatch (C:\Users\BIM02\Desktop\ServerKT\node_modules\koa-compose\index.js:42:32)
[2020-07-13T10:25:20.932] [ERROR] app - ReferenceError: model is not defined
    at Function.Post (C:\Users\BIM02\Desktop\ServerKT\models\index.js:105:5)
    at Object.out.Post (C:\Users\BIM02\Desktop\ServerKT\restful\v0\users.js:42:28)
    at RestfulAPIMethods.(anonymous function) (C:\Users\BIM02\Desktop\ServerKT\routes\restful.js:32:60)
    at dispatch (C:\Users\BIM02\Desktop\ServerKT\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at next (C:\Users\BIM02\Desktop\ServerKT\node_modules\koa-router\node_modules\koa-compose\index.js:45:18)
    at C:\Users\BIM02\Desktop\ServerKT\node_modules\koa-router\lib\router.js:346:16
    at dispatch (C:\Users\BIM02\Desktop\ServerKT\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at next (C:\Users\BIM02\Desktop\ServerKT\node_modules\koa-router\node_modules\koa-compose\index.js:45:18)
    at route.use (C:\Users\BIM02\Desktop\ServerKT\routes\restful.js:97:19)
    at dispatch (C:\Users\BIM02\Desktop\ServerKT\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at next (C:\Users\BIM02\Desktop\ServerKT\node_modules\koa-router\node_modules\koa-compose\index.js:45:18)
    at C:\Users\BIM02\Desktop\ServerKT\node_modules\koa-router\lib\router.js:346:16
    at dispatch (C:\Users\BIM02\Desktop\ServerKT\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at C:\Users\BIM02\Desktop\ServerKT\node_modules\koa-router\node_modules\koa-compose\index.js:36:12
    at dispatch (C:\Users\BIM02\Desktop\ServerKT\node_modules\koa-router\lib\router.js:351:31)
    at dispatch (C:\Users\BIM02\Desktop\ServerKT\node_modules\koa-compose\index.js:42:32)
[2020-07-13T10:34:31.389] [ERROR] app - TypeError: model.toJson is not a function
    at Function.Post (C:\Users\BIM02\Desktop\ServerKT\models\index.js:118:18)
    at Object.out.Post (C:\Users\BIM02\Desktop\ServerKT\restful\v0\users.js:42:31)
    at RestfulAPIMethods.(anonymous function) (C:\Users\BIM02\Desktop\ServerKT\routes\restful.js:32:60)
    at dispatch (C:\Users\BIM02\Desktop\ServerKT\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at next (C:\Users\BIM02\Desktop\ServerKT\node_modules\koa-router\node_modules\koa-compose\index.js:45:18)
    at C:\Users\BIM02\Desktop\ServerKT\node_modules\koa-router\lib\router.js:346:16
    at dispatch (C:\Users\BIM02\Desktop\ServerKT\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at next (C:\Users\BIM02\Desktop\ServerKT\node_modules\koa-router\node_modules\koa-compose\index.js:45:18)
    at route.use (C:\Users\BIM02\Desktop\ServerKT\routes\restful.js:97:19)
    at dispatch (C:\Users\BIM02\Desktop\ServerKT\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at next (C:\Users\BIM02\Desktop\ServerKT\node_modules\koa-router\node_modules\koa-compose\index.js:45:18)
    at C:\Users\BIM02\Desktop\ServerKT\node_modules\koa-router\lib\router.js:346:16
    at dispatch (C:\Users\BIM02\Desktop\ServerKT\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at C:\Users\BIM02\Desktop\ServerKT\node_modules\koa-router\node_modules\koa-compose\index.js:36:12
    at dispatch (C:\Users\BIM02\Desktop\ServerKT\node_modules\koa-router\lib\router.js:351:31)
    at dispatch (C:\Users\BIM02\Desktop\ServerKT\node_modules\koa-compose\index.js:42:32)
[2020-07-13T10:35:59.463] [ERROR] app - Error: Transaction query already complete, run with DEBUG=knex:tx for more info
    at completedError (C:\Users\BIM02\Desktop\ServerKT\node_modules\knex\lib\transaction.js:354:9)
    at C:\Users\BIM02\Desktop\ServerKT\node_modules\knex\lib\transaction.js:320:24
    at new Promise (<anonymous>)
    at Client_MySQL.trxClient.query (C:\Users\BIM02\Desktop\ServerKT\node_modules\knex\lib\transaction.js:316:12)
    at Transaction_MySQL.query (C:\Users\BIM02\Desktop\ServerKT\node_modules\knex\lib\dialects\mysql\transaction.js:12:8)
    at Transaction_MySQL.rollback (C:\Users\BIM02\Desktop\ServerKT\node_modules\knex\lib\transaction.js:98:25)
    at Function.transactor.rollback (C:\Users\BIM02\Desktop\ServerKT\node_modules\knex\lib\transaction.js:278:42)
    at Child.result.then.catch (C:\Users\BIM02\Desktop\ServerKT\node_modules\knex\lib\transaction.js:194:35)
    at Child.tryCatcher (C:\Users\BIM02\Desktop\ServerKT\node_modules\bookshelf\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\BIM02\Desktop\ServerKT\node_modules\bookshelf\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\Users\BIM02\Desktop\ServerKT\node_modules\bookshelf\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\Users\BIM02\Desktop\ServerKT\node_modules\bookshelf\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\Users\BIM02\Desktop\ServerKT\node_modules\bookshelf\node_modules\bluebird\js\release\promise.js:725:18)
    at _drainQueueStep (C:\Users\BIM02\Desktop\ServerKT\node_modules\bookshelf\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\Users\BIM02\Desktop\ServerKT\node_modules\bookshelf\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\Users\BIM02\Desktop\ServerKT\node_modules\bookshelf\node_modules\bluebird\js\release\async.js:102:5)
[2020-07-13T10:36:24.364] [ERROR] app - TypeError: ctx.applog is not a function
    at Post.B.transaction.catch.e (C:\Users\BIM02\Desktop\ServerKT\models\index.js:112:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[2020-07-13T10:36:50.825] [WARN] app - { Error: insert into `user` (`avater`, `id`, `name`, `password`, `phone`, `transacting`, `user`) values (DEFAULT, '9ba354e0-26f4-4001-be2f-bde0d0bc6108', '512313', DEFAULT, '512313', (select *), '4123') - ER_BAD_FIELD_ERROR: Unknown column 'avater' in 'field list'
    at Query.Sequence._packetToError (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
    at Protocol._enqueue (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\protocol\Protocol.js:144:48)
    at Connection.query (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\Connection.js:198:25)
    at C:\Users\BIM02\Desktop\ServerKT\node_modules\knex\lib\dialects\mysql\index.js:135:18
    at new Promise (<anonymous>)
    at Client_MySQL._query (C:\Users\BIM02\Desktop\ServerKT\node_modules\knex\lib\dialects\mysql\index.js:129:12)
    at Client_MySQL.query (C:\Users\BIM02\Desktop\ServerKT\node_modules\knex\lib\client.js:169:17)
    at Runner.query (C:\Users\BIM02\Desktop\ServerKT\node_modules\knex\lib\runner.js:134:36)
    at C:\Users\BIM02\Desktop\ServerKT\node_modules\knex\lib\runner.js:40:23
    at client.acquireConnection.catch.then (C:\Users\BIM02\Desktop\ServerKT\node_modules\knex\lib\runner.js:260:24)
From previous event:
    at Child.<anonymous> (C:\Users\BIM02\Desktop\ServerKT\node_modules\bookshelf\lib\model.js:1160:42)
From previous event:
    at Child.<anonymous> (C:\Users\BIM02\Desktop\ServerKT\node_modules\bookshelf\lib\model.js:1159:14)
    at runCallback (timers.js:694:18)
    at tryOnImmediate (timers.js:665:5)
    at processImmediate (timers.js:647:5)
From previous event:
    at Child.<anonymous> (C:\Users\BIM02\Desktop\ServerKT\node_modules\bookshelf\lib\model.js:1060:10)
From previous event:
    at Post.B.transaction.t (C:\Users\BIM02\Desktop\ServerKT\models\index.js:78:31)
    at init.then.then (C:\Users\BIM02\Desktop\ServerKT\node_modules\knex\lib\transaction.js:184:22)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sqlMessage: 'Unknown column \'avater\' in \'field list\'',
  sqlState: '42S22',
  index: 0,
  sql:
   'insert into `user` (`avater`, `id`, `name`, `password`, `phone`, `transacting`, `user`) values (DEFAULT, \'9ba354e0-26f4-4001-be2f-bde0d0bc6108\', \'512313\', DEFAULT, \'512313\', (select *), \'4123\')' }
[2020-07-13T10:36:50.827] [ERROR] app - { Error: insert into `user` (`avater`, `id`, `name`, `password`, `phone`, `transacting`, `user`) values (DEFAULT, '9ba354e0-26f4-4001-be2f-bde0d0bc6108', '512313', DEFAULT, '512313', (select *), '4123') - ER_BAD_FIELD_ERROR: Unknown column 'avater' in 'field list'
    at Query.Sequence._packetToError (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
    at Protocol._enqueue (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\protocol\Protocol.js:144:48)
    at Connection.query (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\Connection.js:198:25)
    at C:\Users\BIM02\Desktop\ServerKT\node_modules\knex\lib\dialects\mysql\index.js:135:18
    at new Promise (<anonymous>)
    at Client_MySQL._query (C:\Users\BIM02\Desktop\ServerKT\node_modules\knex\lib\dialects\mysql\index.js:129:12)
    at Client_MySQL.query (C:\Users\BIM02\Desktop\ServerKT\node_modules\knex\lib\client.js:169:17)
    at Runner.query (C:\Users\BIM02\Desktop\ServerKT\node_modules\knex\lib\runner.js:134:36)
    at C:\Users\BIM02\Desktop\ServerKT\node_modules\knex\lib\runner.js:40:23
    at client.acquireConnection.catch.then (C:\Users\BIM02\Desktop\ServerKT\node_modules\knex\lib\runner.js:260:24)
From previous event:
    at Child.<anonymous> (C:\Users\BIM02\Desktop\ServerKT\node_modules\bookshelf\lib\model.js:1160:42)
From previous event:
    at Child.<anonymous> (C:\Users\BIM02\Desktop\ServerKT\node_modules\bookshelf\lib\model.js:1159:14)
    at runCallback (timers.js:694:18)
    at tryOnImmediate (timers.js:665:5)
    at processImmediate (timers.js:647:5)
From previous event:
    at Child.<anonymous> (C:\Users\BIM02\Desktop\ServerKT\node_modules\bookshelf\lib\model.js:1060:10)
From previous event:
    at Post.B.transaction.t (C:\Users\BIM02\Desktop\ServerKT\models\index.js:78:31)
    at init.then.then (C:\Users\BIM02\Desktop\ServerKT\node_modules\knex\lib\transaction.js:184:22)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sqlMessage: 'Unknown column \'avater\' in \'field list\'',
  sqlState: '42S22',
  index: 0,
  sql:
   'insert into `user` (`avater`, `id`, `name`, `password`, `phone`, `transacting`, `user`) values (DEFAULT, \'9ba354e0-26f4-4001-be2f-bde0d0bc6108\', \'512313\', DEFAULT, \'512313\', (select *), \'4123\')' }
[2020-07-13T10:37:15.694] [WARN] app - { Error: insert into `user` (`avater`, `id`, `name`, `password`, `phone`, `transacting`, `user`) values (DEFAULT, 'e776d1fd-8876-48b7-aeae-c4425bc13d4c', '512313', DEFAULT, '512313', (select *), '4123') - ER_BAD_FIELD_ERROR: Unknown column 'avater' in 'field list'
    at Query.Sequence._packetToError (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
    at Protocol._enqueue (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\protocol\Protocol.js:144:48)
    at Connection.query (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\Connection.js:198:25)
    at C:\Users\BIM02\Desktop\ServerKT\node_modules\knex\lib\dialects\mysql\index.js:135:18
    at new Promise (<anonymous>)
    at Client_MySQL._query (C:\Users\BIM02\Desktop\ServerKT\node_modules\knex\lib\dialects\mysql\index.js:129:12)
    at Client_MySQL.query (C:\Users\BIM02\Desktop\ServerKT\node_modules\knex\lib\client.js:169:17)
    at Runner.query (C:\Users\BIM02\Desktop\ServerKT\node_modules\knex\lib\runner.js:134:36)
    at C:\Users\BIM02\Desktop\ServerKT\node_modules\knex\lib\runner.js:40:23
    at client.acquireConnection.catch.then (C:\Users\BIM02\Desktop\ServerKT\node_modules\knex\lib\runner.js:260:24)
From previous event:
    at Child.<anonymous> (C:\Users\BIM02\Desktop\ServerKT\node_modules\bookshelf\lib\model.js:1160:42)
From previous event:
    at Child.<anonymous> (C:\Users\BIM02\Desktop\ServerKT\node_modules\bookshelf\lib\model.js:1159:14)
    at runCallback (timers.js:694:18)
    at tryOnImmediate (timers.js:665:5)
    at processImmediate (timers.js:647:5)
From previous event:
    at Child.<anonymous> (C:\Users\BIM02\Desktop\ServerKT\node_modules\bookshelf\lib\model.js:1060:10)
From previous event:
    at Post.B.transaction.t (C:\Users\BIM02\Desktop\ServerKT\models\index.js:78:31)
    at init.then.then (C:\Users\BIM02\Desktop\ServerKT\node_modules\knex\lib\transaction.js:184:22)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sqlMessage: 'Unknown column \'avater\' in \'field list\'',
  sqlState: '42S22',
  index: 0,
  sql:
   'insert into `user` (`avater`, `id`, `name`, `password`, `phone`, `transacting`, `user`) values (DEFAULT, \'e776d1fd-8876-48b7-aeae-c4425bc13d4c\', \'512313\', DEFAULT, \'512313\', (select *), \'4123\')' }
[2020-07-13T10:37:15.697] [ERROR] app - { Error: insert into `user` (`avater`, `id`, `name`, `password`, `phone`, `transacting`, `user`) values (DEFAULT, 'e776d1fd-8876-48b7-aeae-c4425bc13d4c', '512313', DEFAULT, '512313', (select *), '4123') - ER_BAD_FIELD_ERROR: Unknown column 'avater' in 'field list'
    at Query.Sequence._packetToError (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
    at Protocol._enqueue (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\protocol\Protocol.js:144:48)
    at Connection.query (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\Connection.js:198:25)
    at C:\Users\BIM02\Desktop\ServerKT\node_modules\knex\lib\dialects\mysql\index.js:135:18
    at new Promise (<anonymous>)
    at Client_MySQL._query (C:\Users\BIM02\Desktop\ServerKT\node_modules\knex\lib\dialects\mysql\index.js:129:12)
    at Client_MySQL.query (C:\Users\BIM02\Desktop\ServerKT\node_modules\knex\lib\client.js:169:17)
    at Runner.query (C:\Users\BIM02\Desktop\ServerKT\node_modules\knex\lib\runner.js:134:36)
    at C:\Users\BIM02\Desktop\ServerKT\node_modules\knex\lib\runner.js:40:23
    at client.acquireConnection.catch.then (C:\Users\BIM02\Desktop\ServerKT\node_modules\knex\lib\runner.js:260:24)
From previous event:
    at Child.<anonymous> (C:\Users\BIM02\Desktop\ServerKT\node_modules\bookshelf\lib\model.js:1160:42)
From previous event:
    at Child.<anonymous> (C:\Users\BIM02\Desktop\ServerKT\node_modules\bookshelf\lib\model.js:1159:14)
    at runCallback (timers.js:694:18)
    at tryOnImmediate (timers.js:665:5)
    at processImmediate (timers.js:647:5)
From previous event:
    at Child.<anonymous> (C:\Users\BIM02\Desktop\ServerKT\node_modules\bookshelf\lib\model.js:1060:10)
From previous event:
    at Post.B.transaction.t (C:\Users\BIM02\Desktop\ServerKT\models\index.js:78:31)
    at init.then.then (C:\Users\BIM02\Desktop\ServerKT\node_modules\knex\lib\transaction.js:184:22)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sqlMessage: 'Unknown column \'avater\' in \'field list\'',
  sqlState: '42S22',
  index: 0,
  sql:
   'insert into `user` (`avater`, `id`, `name`, `password`, `phone`, `transacting`, `user`) values (DEFAULT, \'e776d1fd-8876-48b7-aeae-c4425bc13d4c\', \'512313\', DEFAULT, \'512313\', (select *), \'4123\')' }
[2020-07-13T10:38:12.413] [WARN] app - { Error: insert into `user` (`id`, `name`, `phone`, `transacting`, `user`) values ('9c31fb99-998f-4f58-beb4-26da8b9a39df', '512313', '512313', (select *), '4123') - ER_BAD_FIELD_ERROR: Unknown column 'transacting' in 'field list'
    at Query.Sequence._packetToError (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
    at Protocol._enqueue (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\protocol\Protocol.js:144:48)
    at Connection.query (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\Connection.js:198:25)
    at C:\Users\BIM02\Desktop\ServerKT\node_modules\knex\lib\dialects\mysql\index.js:135:18
    at new Promise (<anonymous>)
    at Client_MySQL._query (C:\Users\BIM02\Desktop\ServerKT\node_modules\knex\lib\dialects\mysql\index.js:129:12)
    at Client_MySQL.query (C:\Users\BIM02\Desktop\ServerKT\node_modules\knex\lib\client.js:169:17)
    at Runner.query (C:\Users\BIM02\Desktop\ServerKT\node_modules\knex\lib\runner.js:134:36)
    at C:\Users\BIM02\Desktop\ServerKT\node_modules\knex\lib\runner.js:40:23
    at client.acquireConnection.catch.then (C:\Users\BIM02\Desktop\ServerKT\node_modules\knex\lib\runner.js:260:24)
From previous event:
    at Child.<anonymous> (C:\Users\BIM02\Desktop\ServerKT\node_modules\bookshelf\lib\model.js:1160:42)
From previous event:
    at Child.<anonymous> (C:\Users\BIM02\Desktop\ServerKT\node_modules\bookshelf\lib\model.js:1159:14)
    at runCallback (timers.js:694:18)
    at tryOnImmediate (timers.js:665:5)
    at processImmediate (timers.js:647:5)
From previous event:
    at Child.<anonymous> (C:\Users\BIM02\Desktop\ServerKT\node_modules\bookshelf\lib\model.js:1060:10)
From previous event:
    at Post.B.transaction.t (C:\Users\BIM02\Desktop\ServerKT\models\index.js:78:31)
    at init.then.then (C:\Users\BIM02\Desktop\ServerKT\node_modules\knex\lib\transaction.js:184:22)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sqlMessage: 'Unknown column \'transacting\' in \'field list\'',
  sqlState: '42S22',
  index: 0,
  sql:
   'insert into `user` (`id`, `name`, `phone`, `transacting`, `user`) values (\'9c31fb99-998f-4f58-beb4-26da8b9a39df\', \'512313\', \'512313\', (select *), \'4123\')' }
[2020-07-13T10:38:12.415] [ERROR] app - { Error: insert into `user` (`id`, `name`, `phone`, `transacting`, `user`) values ('9c31fb99-998f-4f58-beb4-26da8b9a39df', '512313', '512313', (select *), '4123') - ER_BAD_FIELD_ERROR: Unknown column 'transacting' in 'field list'
    at Query.Sequence._packetToError (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
    at Protocol._enqueue (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\protocol\Protocol.js:144:48)
    at Connection.query (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\Connection.js:198:25)
    at C:\Users\BIM02\Desktop\ServerKT\node_modules\knex\lib\dialects\mysql\index.js:135:18
    at new Promise (<anonymous>)
    at Client_MySQL._query (C:\Users\BIM02\Desktop\ServerKT\node_modules\knex\lib\dialects\mysql\index.js:129:12)
    at Client_MySQL.query (C:\Users\BIM02\Desktop\ServerKT\node_modules\knex\lib\client.js:169:17)
    at Runner.query (C:\Users\BIM02\Desktop\ServerKT\node_modules\knex\lib\runner.js:134:36)
    at C:\Users\BIM02\Desktop\ServerKT\node_modules\knex\lib\runner.js:40:23
    at client.acquireConnection.catch.then (C:\Users\BIM02\Desktop\ServerKT\node_modules\knex\lib\runner.js:260:24)
From previous event:
    at Child.<anonymous> (C:\Users\BIM02\Desktop\ServerKT\node_modules\bookshelf\lib\model.js:1160:42)
From previous event:
    at Child.<anonymous> (C:\Users\BIM02\Desktop\ServerKT\node_modules\bookshelf\lib\model.js:1159:14)
    at runCallback (timers.js:694:18)
    at tryOnImmediate (timers.js:665:5)
    at processImmediate (timers.js:647:5)
From previous event:
    at Child.<anonymous> (C:\Users\BIM02\Desktop\ServerKT\node_modules\bookshelf\lib\model.js:1060:10)
From previous event:
    at Post.B.transaction.t (C:\Users\BIM02\Desktop\ServerKT\models\index.js:78:31)
    at init.then.then (C:\Users\BIM02\Desktop\ServerKT\node_modules\knex\lib\transaction.js:184:22)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sqlMessage: 'Unknown column \'transacting\' in \'field list\'',
  sqlState: '42S22',
  index: 0,
  sql:
   'insert into `user` (`id`, `name`, `phone`, `transacting`, `user`) values (\'9c31fb99-998f-4f58-beb4-26da8b9a39df\', \'512313\', \'512313\', (select *), \'4123\')' }
[2020-07-13T10:38:52.886] [WARN] app - TypeError: this.save is not a function
    at Post.B.transaction.t (C:\Users\BIM02\Desktop\ServerKT\models\index.js:78:19)
    at init.then.then (C:\Users\BIM02\Desktop\ServerKT\node_modules\knex\lib\transaction.js:184:22)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[2020-07-13T10:38:52.887] [ERROR] app - TypeError: this.save is not a function
    at Post.B.transaction.t (C:\Users\BIM02\Desktop\ServerKT\models\index.js:78:19)
    at init.then.then (C:\Users\BIM02\Desktop\ServerKT\node_modules\knex\lib\transaction.js:184:22)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[2020-07-13T10:39:04.665] [ERROR] app - { key: 'user', error: '用户注册失败:用户名已存在' }
[2020-07-13T10:39:12.357] [ERROR] app - TypeError: model.toJson is not a function
    at Function.Post (C:\Users\BIM02\Desktop\ServerKT\models\index.js:117:18)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[2020-07-13T10:39:45.738] [ERROR] app - { key: 'user', error: '用户注册失败:用户名已存在' }
[2020-07-13T10:39:49.793] [ERROR] app - { key: 'phone', error: '用户注册失败:电话号码已存在' }
[2020-07-13T10:39:58.080] [ERROR] app - { key: 'phone', error: '用户注册失败:电话号码已存在' }
[2020-07-13T10:40:17.043] [ERROR] app - { key: 'phone', error: '用户注册失败:电话号码已存在' }
[2020-07-13T10:41:48.649] [ERROR] app - ReferenceError: Debug is not defined
    at Post.B.transaction.catch.e (C:\Users\BIM02\Desktop\ServerKT\models\index.js:103:7)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[2020-07-13T10:42:13.237] [ERROR] app - { key: 'phone', error: '用户注册失败:电话号码已存在' }
[2020-07-13T10:43:11.217] [ERROR] app - TypeError: model.toJson is not a function
    at Function.Post (C:\Users\BIM02\Desktop\ServerKT\models\index.js:118:18)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[2020-07-13T10:47:15.857] [WARN] app - { Error: insert into `user` (`created_at`, `id`, `name`, `phone`, `updated_at`, `user`) values ('2020-07-13 10:47:15.830', '2e2f0850-05a1-4503-8cbd-ae9d60f9fa8e', '12414', '551231', '2020-07-13 10:47:15.830', '51234') - ER_BAD_FIELD_ERROR: Unknown column 'updated_at' in 'field list'
    at Query.Sequence._packetToError (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
    at Protocol._enqueue (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\protocol\Protocol.js:144:48)
    at Connection.query (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\Connection.js:198:25)
    at C:\Users\BIM02\Desktop\ServerKT\node_modules\knex\lib\dialects\mysql\index.js:135:18
    at new Promise (<anonymous>)
    at Client_MySQL._query (C:\Users\BIM02\Desktop\ServerKT\node_modules\knex\lib\dialects\mysql\index.js:129:12)
    at Client_MySQL.query (C:\Users\BIM02\Desktop\ServerKT\node_modules\knex\lib\client.js:169:17)
    at C:\Users\BIM02\Desktop\ServerKT\node_modules\knex\lib\transaction.js:321:24
    at new Promise (<anonymous>)
    at Client_MySQL.trxClient.query (C:\Users\BIM02\Desktop\ServerKT\node_modules\knex\lib\transaction.js:316:12)
    at Runner.query (C:\Users\BIM02\Desktop\ServerKT\node_modules\knex\lib\runner.js:134:36)
    at C:\Users\BIM02\Desktop\ServerKT\node_modules\knex\lib\runner.js:40:23
    at client.acquireConnection.catch.then (C:\Users\BIM02\Desktop\ServerKT\node_modules\knex\lib\runner.js:260:24)
From previous event:
    at Child.<anonymous> (C:\Users\BIM02\Desktop\ServerKT\node_modules\bookshelf\lib\model.js:1160:42)
From previous event:
    at Child.<anonymous> (C:\Users\BIM02\Desktop\ServerKT\node_modules\bookshelf\lib\model.js:1159:14)
    at runCallback (timers.js:694:18)
    at tryOnImmediate (timers.js:665:5)
    at processImmediate (timers.js:647:5)
From previous event:
    at Child.<anonymous> (C:\Users\BIM02\Desktop\ServerKT\node_modules\bookshelf\lib\model.js:1060:10)
From previous event:
    at Post.B.transaction.t (C:\Users\BIM02\Desktop\ServerKT\models\index.js:78:27)
    at init.then.then (C:\Users\BIM02\Desktop\ServerKT\node_modules\knex\lib\transaction.js:184:22)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sqlMessage: 'Unknown column \'updated_at\' in \'field list\'',
  sqlState: '42S22',
  index: 0,
  sql:
   'insert into `user` (`created_at`, `id`, `name`, `phone`, `updated_at`, `user`) values (\'2020-07-13 10:47:15.830\', \'2e2f0850-05a1-4503-8cbd-ae9d60f9fa8e\', \'12414\', \'551231\', \'2020-07-13 10:47:15.830\', \'51234\')' }
[2020-07-13T10:47:15.860] [ERROR] app - { Error: insert into `user` (`created_at`, `id`, `name`, `phone`, `updated_at`, `user`) values ('2020-07-13 10:47:15.830', '2e2f0850-05a1-4503-8cbd-ae9d60f9fa8e', '12414', '551231', '2020-07-13 10:47:15.830', '51234') - ER_BAD_FIELD_ERROR: Unknown column 'updated_at' in 'field list'
    at Query.Sequence._packetToError (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
    at Protocol._enqueue (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\protocol\Protocol.js:144:48)
    at Connection.query (C:\Users\BIM02\Desktop\ServerKT\node_modules\mysql\lib\Connection.js:198:25)
    at C:\Users\BIM02\Desktop\ServerKT\node_modules\knex\lib\dialects\mysql\index.js:135:18
    at new Promise (<anonymous>)
    at Client_MySQL._query (C:\Users\BIM02\Desktop\ServerKT\node_modules\knex\lib\dialects\mysql\index.js:129:12)
    at Client_MySQL.query (C:\Users\BIM02\Desktop\ServerKT\node_modules\knex\lib\client.js:169:17)
    at C:\Users\BIM02\Desktop\ServerKT\node_modules\knex\lib\transaction.js:321:24
    at new Promise (<anonymous>)
    at Client_MySQL.trxClient.query (C:\Users\BIM02\Desktop\ServerKT\node_modules\knex\lib\transaction.js:316:12)
    at Runner.query (C:\Users\BIM02\Desktop\ServerKT\node_modules\knex\lib\runner.js:134:36)
    at C:\Users\BIM02\Desktop\ServerKT\node_modules\knex\lib\runner.js:40:23
    at client.acquireConnection.catch.then (C:\Users\BIM02\Desktop\ServerKT\node_modules\knex\lib\runner.js:260:24)
From previous event:
    at Child.<anonymous> (C:\Users\BIM02\Desktop\ServerKT\node_modules\bookshelf\lib\model.js:1160:42)
From previous event:
    at Child.<anonymous> (C:\Users\BIM02\Desktop\ServerKT\node_modules\bookshelf\lib\model.js:1159:14)
    at runCallback (timers.js:694:18)
    at tryOnImmediate (timers.js:665:5)
    at processImmediate (timers.js:647:5)
From previous event:
    at Child.<anonymous> (C:\Users\BIM02\Desktop\ServerKT\node_modules\bookshelf\lib\model.js:1060:10)
From previous event:
    at Post.B.transaction.t (C:\Users\BIM02\Desktop\ServerKT\models\index.js:78:27)
    at init.then.then (C:\Users\BIM02\Desktop\ServerKT\node_modules\knex\lib\transaction.js:184:22)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sqlMessage: 'Unknown column \'updated_at\' in \'field list\'',
  sqlState: '42S22',
  index: 0,
  sql:
   'insert into `user` (`created_at`, `id`, `name`, `phone`, `updated_at`, `user`) values (\'2020-07-13 10:47:15.830\', \'2e2f0850-05a1-4503-8cbd-ae9d60f9fa8e\', \'12414\', \'551231\', \'2020-07-13 10:47:15.830\', \'51234\')' }
[2020-07-13T13:20:11.314] [ERROR] app - 没有访问权限
[2020-07-13T13:20:27.627] [ERROR] app - 没有访问权限
[2020-07-13T14:32:56.528] [ERROR] app - 没有访问权限
