[2020-04-09T08:28:52.996] [ERROR] app - { Error: ER_BAD_FIELD_ERROR: Unknown column 'order000000000V9' in 'field list'
    at Query.Sequence._packetToError (D:\able_project\CloudServer\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (D:\able_project\CloudServer\node_modules\mysql\lib\protocol\sequences\Query.js:77:18)
    at Protocol._parsePacket (D:\able_project\CloudServer\node_modules\mysql\lib\protocol\Protocol.js:278:23)
    at Parser.write (D:\able_project\CloudServer\node_modules\mysql\lib\protocol\Parser.js:76:12)
    at Protocol.write (D:\able_project\CloudServer\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (D:\able_project\CloudServer\node_modules\mysql\lib\Connection.js:91:28)
    at Socket.<anonymous> (D:\able_project\CloudServer\node_modules\mysql\lib\Connection.js:502:10)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
    at Protocol._enqueue (D:\able_project\CloudServer\node_modules\mysql\lib\protocol\Protocol.js:144:48)
    at Connection.query (D:\able_project\CloudServer\node_modules\mysql\lib\Connection.js:200:25)
    at D:\able_project\CloudServer\node_modules\knex\lib\dialects\mysql\index.js:152:18
From previous event:
    at Client_MySQL._query (D:\able_project\CloudServer\node_modules\knex\lib\dialects\mysql\index.js:146:12)
    at Client_MySQL.query (D:\able_project\CloudServer\node_modules\knex\lib\client.js:197:17)
    at Runner.<anonymous> (D:\able_project\CloudServer\node_modules\knex\lib\runner.js:146:36)
From previous event:
    at D:\able_project\CloudServer\node_modules\knex\lib\runner.js:65:21
    at runCallback (timers.js:694:18)
    at tryOnImmediate (timers.js:665:5)
From previous event:
    at Runner.run (D:\able_project\CloudServer\node_modules\knex\lib\runner.js:51:31)
    at Builder.Target.then (D:\able_project\CloudServer\node_modules\knex\lib\interface.js:35:43)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sqlMessage: 'Unknown column \'order000000000V9\' in \'field list\'',
  sqlState: '42S22',
  index: 0,
  sql:
   'insert into `reply` (`id`, `inputTime`, `inputor`, `order000000000V9`, `order_id`) values (\'CMT00000000000VF\', \'2020-04-09T08:28:52+08:00\', \'UID00000001\', \'\', \'undefined\')' }
[2020-04-09T08:30:56.199] [INFO] app - *** SYSTEM STARTUP on PORT (5858) ***
[2020-04-09T08:30:57.920] [ERROR] app - { Error: ER_BAD_FIELD_ERROR: Unknown column 'order000000000V9' in 'field list'
    at Query.Sequence._packetToError (D:\able_project\CloudServer\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (D:\able_project\CloudServer\node_modules\mysql\lib\protocol\sequences\Query.js:77:18)
    at Protocol._parsePacket (D:\able_project\CloudServer\node_modules\mysql\lib\protocol\Protocol.js:278:23)
    at Parser.write (D:\able_project\CloudServer\node_modules\mysql\lib\protocol\Parser.js:76:12)
    at Protocol.write (D:\able_project\CloudServer\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (D:\able_project\CloudServer\node_modules\mysql\lib\Connection.js:91:28)
    at Socket.<anonymous> (D:\able_project\CloudServer\node_modules\mysql\lib\Connection.js:502:10)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
    at Protocol._enqueue (D:\able_project\CloudServer\node_modules\mysql\lib\protocol\Protocol.js:144:48)
    at Connection.query (D:\able_project\CloudServer\node_modules\mysql\lib\Connection.js:200:25)
    at D:\able_project\CloudServer\node_modules\knex\lib\dialects\mysql\index.js:152:18
From previous event:
    at Client_MySQL._query (D:\able_project\CloudServer\node_modules\knex\lib\dialects\mysql\index.js:146:12)
    at Client_MySQL.query (D:\able_project\CloudServer\node_modules\knex\lib\client.js:197:17)
    at Runner.<anonymous> (D:\able_project\CloudServer\node_modules\knex\lib\runner.js:146:36)
From previous event:
    at D:\able_project\CloudServer\node_modules\knex\lib\runner.js:65:21
    at runCallback (timers.js:694:18)
    at tryOnImmediate (timers.js:665:5)
From previous event:
    at Runner.run (D:\able_project\CloudServer\node_modules\knex\lib\runner.js:51:31)
    at Builder.Target.then (D:\able_project\CloudServer\node_modules\knex\lib\interface.js:35:43)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sqlMessage: 'Unknown column \'order000000000V9\' in \'field list\'',
  sqlState: '42S22',
  index: 0,
  sql:
   'insert into `reply` (`id`, `inputTime`, `inputor`, `order000000000V9`, `order_id`) values (\'CMT00000000000VH\', \'2020-04-09T08:30:57+08:00\', \'UID00000001\', \'\', \'undefined\')' }
[2020-04-09T08:34:35.169] [ERROR] app - Request without token
[2020-04-09T08:34:35.171] [ERROR] app - 没有访问权限
[2020-04-09T10:37:12.782] [ERROR] app - Request without token
[2020-04-09T10:37:12.783] [ERROR] app - 没有访问权限
[2020-04-09T10:40:49.499] [INFO] app - *** SYSTEM STARTUP on PORT (5858) ***
[2020-04-09T10:40:55.312] [INFO] app - *** SYSTEM STARTUP on PORT (5858) ***
[2020-04-09T10:40:58.517] [INFO] app - *** SYSTEM STARTUP on PORT (5858) ***
[2020-04-09T10:41:01.702] [ERROR] app - Request without token
[2020-04-09T10:41:01.705] [ERROR] app - 没有访问权限
[2020-04-09T10:58:17.080] [ERROR] app - Request without token
[2020-04-09T10:58:17.082] [ERROR] app - 没有访问权限
[2020-04-09T10:59:42.432] [ERROR] app - Request without token
[2020-04-09T10:59:42.434] [ERROR] app - 没有访问权限
[2020-04-09T14:04:58.040] [ERROR] app - 401
[2020-04-09T14:04:58.406] [ERROR] app - 401
[2020-04-09T14:04:58.656] [ERROR] app - Request without token
[2020-04-09T14:04:58.660] [ERROR] app - 没有访问权限
[2020-04-09T14:04:58.677] [ERROR] app - 401
[2020-04-09T14:04:58.685] [ERROR] app - 401
[2020-04-09T14:05:00.449] [ERROR] app - 401
[2020-04-09T14:05:00.530] [ERROR] app - 401
[2020-04-09T14:05:06.642] [ERROR] app - 401
[2020-04-09T14:07:21.358] [INFO] app - *** SYSTEM STARTUP on PORT (5858) ***
[2020-04-09T14:11:02.970] [ERROR] app - 401
[2020-04-09T14:11:03.126] [ERROR] app - 401
[2020-04-09T14:11:03.302] [ERROR] app - Request without token
[2020-04-09T14:11:03.304] [ERROR] app - 没有访问权限
[2020-04-09T14:11:03.320] [ERROR] app - 401
[2020-04-09T14:11:03.324] [ERROR] app - 401
[2020-04-09T14:14:06.056] [INFO] app - *** SYSTEM STARTUP on PORT (5858) ***
[2020-04-09T14:14:07.972] [ERROR] app - { Error: ER_BAD_FIELD_ERROR: Unknown column 'order_id' in 'where clause'
    at Query.Sequence._packetToError (D:\able_project\CloudServer\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (D:\able_project\CloudServer\node_modules\mysql\lib\protocol\sequences\Query.js:77:18)
    at Protocol._parsePacket (D:\able_project\CloudServer\node_modules\mysql\lib\protocol\Protocol.js:278:23)
    at Parser.write (D:\able_project\CloudServer\node_modules\mysql\lib\protocol\Parser.js:76:12)
    at Protocol.write (D:\able_project\CloudServer\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (D:\able_project\CloudServer\node_modules\mysql\lib\Connection.js:91:28)
    at Socket.<anonymous> (D:\able_project\CloudServer\node_modules\mysql\lib\Connection.js:502:10)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
    at Protocol._enqueue (D:\able_project\CloudServer\node_modules\mysql\lib\protocol\Protocol.js:144:48)
    at Connection.query (D:\able_project\CloudServer\node_modules\mysql\lib\Connection.js:200:25)
    at D:\able_project\CloudServer\node_modules\knex\lib\dialects\mysql\index.js:152:18
From previous event:
    at Client_MySQL._query (D:\able_project\CloudServer\node_modules\knex\lib\dialects\mysql\index.js:146:12)
    at Client_MySQL.query (D:\able_project\CloudServer\node_modules\knex\lib\client.js:197:17)
    at Runner.<anonymous> (D:\able_project\CloudServer\node_modules\knex\lib\runner.js:146:36)
From previous event:
    at D:\able_project\CloudServer\node_modules\knex\lib\runner.js:65:21
    at runCallback (timers.js:694:18)
    at tryOnImmediate (timers.js:665:5)
From previous event:
    at Runner.run (D:\able_project\CloudServer\node_modules\knex\lib\runner.js:51:31)
    at Builder.Target.then (D:\able_project\CloudServer\node_modules\knex\lib\interface.js:35:43)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sqlMessage: 'Unknown column \'order_id\' in \'where clause\'',
  sqlState: '42S22',
  index: 0,
  sql:
   'update `order` set `state` = 1 where `order_id` = \'order000000000V9\'' }
[2020-04-09T14:14:22.496] [INFO] app - *** SYSTEM STARTUP on PORT (5858) ***
[2020-04-09T14:16:31.253] [ERROR] app - Request without token
[2020-04-09T14:16:31.255] [ERROR] app - 没有访问权限
[2020-04-09T14:18:21.497] [ERROR] app - Request without token
[2020-04-09T14:18:21.499] [ERROR] app - 没有访问权限
[2020-04-09T14:22:12.869] [ERROR] app - Request without token
[2020-04-09T14:22:12.870] [ERROR] app - 没有访问权限
[2020-04-09T15:30:43.667] [ERROR] app - Request without token
[2020-04-09T15:30:43.668] [ERROR] app - 没有访问权限
[2020-04-09T15:32:25.566] [ERROR] app - Request without token
[2020-04-09T15:32:25.567] [ERROR] app - 没有访问权限
[2020-04-09T15:43:46.370] [ERROR] app - Request without token
[2020-04-09T15:43:46.372] [ERROR] app - 没有访问权限
[2020-04-09T15:44:38.981] [ERROR] app - 401
[2020-04-09T15:44:38.983] [ERROR] app - 401
[2020-04-09T15:44:39.170] [ERROR] app - Request without token
[2020-04-09T15:44:39.171] [ERROR] app - 没有访问权限
[2020-04-09T15:44:39.189] [ERROR] app - 401
[2020-04-09T15:44:39.193] [ERROR] app - 401
