[2021-02-04T00:00:19.654] [ERROR] app - 401
[2021-02-04T00:00:19.658] [ERROR] app - 401
[2021-02-04T00:01:37.908] [ERROR] app - 401
[2021-02-04T00:02:23.141] [ERROR] app - 401
[2021-02-04T00:02:23.143] [ERROR] app - 401
[2021-02-04T00:02:30.519] [ERROR] app - 401
[2021-02-04T00:02:32.057] [ERROR] app - 401
[2021-02-04T00:02:34.412] [ERROR] app - 401
[2021-02-04T00:02:35.656] [ERROR] app - 401
[2021-02-04T00:02:38.330] [ERROR] app - 401
[2021-02-04T00:02:41.584] [ERROR] app - 401
[2021-02-04T00:02:47.813] [ERROR] app - 401
[2021-02-04T00:02:47.817] [ERROR] app - 401
[2021-02-04T00:04:14.788] [ERROR] app - 401
[2021-02-04T00:04:14.792] [ERROR] app - 401
[2021-02-04T00:06:21.515] [ERROR] app - 401
[2021-02-04T00:06:21.518] [ERROR] app - 401
[2021-02-04T00:08:08.266] [ERROR] app - 401
[2021-02-04T00:08:08.271] [ERROR] app - 401
[2021-02-04T00:11:56.307] [ERROR] app - Error: ER_BAD_FIELD_ERROR: Unknown column 'important_raw' in 'field list'
    at Query.Sequence._packetToError (C:\Users\racky\Desktop\project\hstigger-server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\racky\Desktop\project\hstigger-server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\racky\Desktop\project\hstigger-server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\racky\Desktop\project\hstigger-server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\racky\Desktop\project\hstigger-server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\racky\Desktop\project\hstigger-server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\racky\Desktop\project\hstigger-server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\racky\Desktop\project\hstigger-server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:311:20)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at Socket.Readable.push (_stream_readable.js:209:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
    at Protocol._enqueue (C:\Users\racky\Desktop\project\hstigger-server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:144:48)
    at Connection.query (C:\Users\racky\Desktop\project\hstigger-server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:198:25)
    at C:\Users\racky\Desktop\project\hstigger-server\node_modules\_knex@0.13.0@knex\lib\dialects\mysql\index.js:152:18
    at Promise._execute (C:\Users\racky\Desktop\project\hstigger-server\node_modules\_bluebird@3.7.2@bluebird\js\release\debuggability.js:384:9)
    at Promise._resolveFromExecutor (C:\Users\racky\Desktop\project\hstigger-server\node_modules\_bluebird@3.7.2@bluebird\js\release\promise.js:518:18)
From previous event:
    at Promise.longStackTracesCaptureStackTrace [as _captureStackTrace] (C:\Users\racky\Desktop\project\hstigger-server\node_modules\_bluebird@3.7.2@bluebird\js\release\debuggability.js:482:19)
    at Promise._then (C:\Users\racky\Desktop\project\hstigger-server\node_modules\_bluebird@3.7.2@bluebird\js\release\promise.js:261:17)
    at Promise._passThrough (C:\Users\racky\Desktop\project\hstigger-server\node_modules\_bluebird@3.7.2@bluebird\js\release\finally.js:94:17)
    at Promise.lastly.Promise.finally (C:\Users\racky\Desktop\project\hstigger-server\node_modules\_bluebird@3.7.2@bluebird\js\release\finally.js:103:17)
    at Function.Promise.using (C:\Users\racky\Desktop\project\hstigger-server\node_modules\_bluebird@3.7.2@bluebird\js\release\using.js:192:37)
    at Runner.run (C:\Users\racky\Desktop\project\hstigger-server\node_modules\_knex@0.13.0@knex\lib\runner.js:51:31)
    at Builder.Target.then (C:\Users\racky\Desktop\project\hstigger-server\node_modules\_knex@0.13.0@knex\lib\interface.js:35:43) {
  code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sqlMessage: "Unknown column 'important_raw' in 'field list'",
  sqlState: '42S22',
  index: 0,
  sql: "update `ENT_aee3eea0_3b83_11eb_8e1e_c15d5c7db744`.`contract` set `file` = '12月9日合约系统汇报.pptx,https://nbgzfiles-1257839135.cos.ap-shanghai.myqcloud.com//files/ref/2021-02-04/81521a70-663a-11eb-aaf6-e72e2f9cf205.pptx,pptx', `file_assurance` = 'jbkt.png,https://nbgzfiles-1257839135.cos.ap-shanghai.myqcloud.com//files/ref/2021-02-04/872cf960-663a-11eb-aaf6-e72e2f9cf205.png,png', `important_raw` = '23423', `partB` = 'NBGZ', `pay_condition_raw` = '423425', `register_date` = '2021-02-03' where `id` = '2b3679d0-6115-11eb-83e7-0fe0104f99e2'"
}
[2021-02-04T00:13:03.030] [ERROR] app - 401
[2021-02-04T00:13:03.033] [ERROR] app - 401
[2021-02-04T00:18:06.254] [ERROR] app - 401
[2021-02-04T00:18:10.059] [ERROR] app - 401
[2021-02-04T00:18:10.062] [ERROR] app - 401
[2021-02-04T00:27:50.404] [ERROR] app - Error: ER_BAD_FIELD_ERROR: Unknown column 'desc' in 'field list'
    at Query.Sequence._packetToError (C:\Users\racky\Desktop\project\hstigger-server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\racky\Desktop\project\hstigger-server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\racky\Desktop\project\hstigger-server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\racky\Desktop\project\hstigger-server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\racky\Desktop\project\hstigger-server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\racky\Desktop\project\hstigger-server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\racky\Desktop\project\hstigger-server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\racky\Desktop\project\hstigger-server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:311:20)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at Socket.Readable.push (_stream_readable.js:209:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
    at Protocol._enqueue (C:\Users\racky\Desktop\project\hstigger-server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:144:48)
    at Connection.query (C:\Users\racky\Desktop\project\hstigger-server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:198:25)
    at C:\Users\racky\Desktop\project\hstigger-server\node_modules\_knex@0.13.0@knex\lib\dialects\mysql\index.js:152:18
    at Promise._execute (C:\Users\racky\Desktop\project\hstigger-server\node_modules\_bluebird@3.7.2@bluebird\js\release\debuggability.js:384:9)
    at Promise._resolveFromExecutor (C:\Users\racky\Desktop\project\hstigger-server\node_modules\_bluebird@3.7.2@bluebird\js\release\promise.js:518:18)
From previous event:
    at Promise.longStackTracesCaptureStackTrace [as _captureStackTrace] (C:\Users\racky\Desktop\project\hstigger-server\node_modules\_bluebird@3.7.2@bluebird\js\release\debuggability.js:482:19)
    at Promise._then (C:\Users\racky\Desktop\project\hstigger-server\node_modules\_bluebird@3.7.2@bluebird\js\release\promise.js:261:17)
    at Promise._passThrough (C:\Users\racky\Desktop\project\hstigger-server\node_modules\_bluebird@3.7.2@bluebird\js\release\finally.js:94:17)
    at Promise.lastly.Promise.finally (C:\Users\racky\Desktop\project\hstigger-server\node_modules\_bluebird@3.7.2@bluebird\js\release\finally.js:103:17)
    at Function.Promise.using (C:\Users\racky\Desktop\project\hstigger-server\node_modules\_bluebird@3.7.2@bluebird\js\release\using.js:192:37)
    at Runner.run (C:\Users\racky\Desktop\project\hstigger-server\node_modules\_knex@0.13.0@knex\lib\runner.js:51:31)
    at Builder.Target.then (C:\Users\racky\Desktop\project\hstigger-server\node_modules\_knex@0.13.0@knex\lib\interface.js:35:43) {
  code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sqlMessage: "Unknown column 'desc' in 'field list'",
  sqlState: '42S22',
  index: 0,
  sql: "insert into `ENT_aee3eea0_3b83_11eb_8e1e_c15d5c7db744`.`project` (`charger`, `code`, `created_at`, `created_by`, `desc`, `id`, `name`, `shortname`, `state`) values ('TEST', '202013', '2021-02-04 00:27:50', 'TEST', '/public/upload/20200616/20200616_5ee8cbd370c11.pdf', 'c1fe46f0-663c-11eb-91fd-5d0fdc5c313a', '慈城古城保黎医院综合改造工程', '保黎医院', 0)"
}
[2021-02-04T00:28:05.937] [ERROR] app - Error: ER_BAD_FIELD_ERROR: Unknown column 'desc' in 'field list'
    at Query.Sequence._packetToError (C:\Users\racky\Desktop\project\hstigger-server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\racky\Desktop\project\hstigger-server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\racky\Desktop\project\hstigger-server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\racky\Desktop\project\hstigger-server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\racky\Desktop\project\hstigger-server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\racky\Desktop\project\hstigger-server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\racky\Desktop\project\hstigger-server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\racky\Desktop\project\hstigger-server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:311:20)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at Socket.Readable.push (_stream_readable.js:209:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
    at Protocol._enqueue (C:\Users\racky\Desktop\project\hstigger-server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:144:48)
    at Connection.query (C:\Users\racky\Desktop\project\hstigger-server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:198:25)
    at C:\Users\racky\Desktop\project\hstigger-server\node_modules\_knex@0.13.0@knex\lib\dialects\mysql\index.js:152:18
    at Promise._execute (C:\Users\racky\Desktop\project\hstigger-server\node_modules\_bluebird@3.7.2@bluebird\js\release\debuggability.js:384:9)
    at Promise._resolveFromExecutor (C:\Users\racky\Desktop\project\hstigger-server\node_modules\_bluebird@3.7.2@bluebird\js\release\promise.js:518:18)
From previous event:
    at Promise.longStackTracesCaptureStackTrace [as _captureStackTrace] (C:\Users\racky\Desktop\project\hstigger-server\node_modules\_bluebird@3.7.2@bluebird\js\release\debuggability.js:482:19)
    at Promise._then (C:\Users\racky\Desktop\project\hstigger-server\node_modules\_bluebird@3.7.2@bluebird\js\release\promise.js:261:17)
    at Promise._passThrough (C:\Users\racky\Desktop\project\hstigger-server\node_modules\_bluebird@3.7.2@bluebird\js\release\finally.js:94:17)
    at Promise.lastly.Promise.finally (C:\Users\racky\Desktop\project\hstigger-server\node_modules\_bluebird@3.7.2@bluebird\js\release\finally.js:103:17)
    at Function.Promise.using (C:\Users\racky\Desktop\project\hstigger-server\node_modules\_bluebird@3.7.2@bluebird\js\release\using.js:192:37)
    at Runner.run (C:\Users\racky\Desktop\project\hstigger-server\node_modules\_knex@0.13.0@knex\lib\runner.js:51:31)
    at Builder.Target.then (C:\Users\racky\Desktop\project\hstigger-server\node_modules\_knex@0.13.0@knex\lib\interface.js:35:43) {
  code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sqlMessage: "Unknown column 'desc' in 'field list'",
  sqlState: '42S22',
  index: 0,
  sql: "insert into `ENT_aee3eea0_3b83_11eb_8e1e_c15d5c7db744`.`project` (`charger`, `code`, `created_at`, `created_by`, `desc`, `id`, `name`, `shortname`, `state`) values ('TEST', '202013', '2021-02-04 00:28:05', 'TEST', '', 'cb410900-663c-11eb-91fd-5d0fdc5c313a', '慈城古城保黎医院综合改造工程', '保黎医院', 0)"
}
[2021-02-04T00:29:14.272] [ERROR] app - 401
[2021-02-04T00:29:14.273] [ERROR] app - 401
[2021-02-04T00:29:14.276] [ERROR] app - 401
[2021-02-04T00:29:15.411] [ERROR] app - 401
[2021-02-04T00:29:23.555] [ERROR] app - 401
[2021-02-04T00:29:23.558] [ERROR] app - 401
[2021-02-04T00:34:32.455] [ERROR] app - 数据传输错误,请联系管理员
[2021-02-04T00:34:38.921] [ERROR] app - 数据传输错误,请联系管理员
[2021-02-04T00:34:45.105] [ERROR] app - 数据传输错误,请联系管理员
[2021-02-04T00:35:26.901] [ERROR] app - 数据传输错误,请联系管理员
[2021-02-04T00:35:43.057] [ERROR] app - 数据传输错误,请联系管理员
[2021-02-04T00:37:52.771] [ERROR] app - 401
[2021-02-04T00:37:52.784] [ERROR] app - 401
[2021-02-04T00:37:58.924] [ERROR] app - 数据传输错误,请联系管理员
[2021-02-04T00:38:08.477] [ERROR] app - 数据传输错误,请联系管理员
[2021-02-04T00:38:43.723] [ERROR] app - 401
[2021-02-04T00:38:43.728] [ERROR] app - 401
[2021-02-04T00:38:48.475] [ERROR] app - 数据传输错误,请联系管理员
[2021-02-04T00:38:54.028] [ERROR] app - 数据传输错误,请联系管理员
[2021-02-04T00:39:02.788] [ERROR] app - 数据传输错误,请联系管理员
[2021-02-04T00:39:53.905] [ERROR] app - 401
[2021-02-04T00:39:53.909] [ERROR] app - 401
[2021-02-04T00:39:58.958] [ERROR] app - 数据传输错误,请联系管理员
[2021-02-04T00:40:19.757] [ERROR] app - 401
[2021-02-04T00:40:19.761] [ERROR] app - 401
[2021-02-04T00:40:26.239] [ERROR] app - 数据传输错误,请联系管理员
[2021-02-04T00:41:49.104] [ERROR] app - 401
[2021-02-04T00:42:17.043] [ERROR] app - 数据传输错误,请联系管理员
[2021-02-04T00:42:57.263] [ERROR] app - 数据传输错误,请联系管理员
[2021-02-04T00:48:59.500] [ERROR] app - 数据传输错误,请联系管理员
[2021-02-04T00:49:02.621] [ERROR] app - 数据传输错误,请联系管理员
[2021-02-04T00:49:14.990] [ERROR] app - 数据传输错误,请联系管理员
[2021-02-04T00:49:23.208] [ERROR] app - 数据传输错误,请联系管理员
[2021-02-04T00:50:27.406] [ERROR] app - 数据传输错误,请联系管理员
[2021-02-04T00:50:35.791] [ERROR] app - 数据传输错误,请联系管理员
[2021-02-04T00:50:39.238] [ERROR] app - 数据传输错误,请联系管理员
[2021-02-04T00:50:44.815] [ERROR] app - 数据传输错误,请联系管理员
[2021-02-04T00:52:34.607] [ERROR] app - 数据传输错误,请联系管理员
[2021-02-04T01:01:09.352] [ERROR] app - 数据传输错误,请联系管理员
[2021-02-04T01:09:18.065] [ERROR] app - 数据传输错误,请联系管理员
[2021-02-04T01:20:16.929] [ERROR] app - 附件不合法:undefined
[2021-02-04T01:21:19.902] [ERROR] app - 数据传输错误,请联系管理员
[2021-02-04T01:21:23.317] [ERROR] app - 数据传输错误,请联系管理员
[2021-02-04T01:24:50.436] [ERROR] app - 401
[2021-02-04T01:24:50.440] [ERROR] app - 401
[2021-02-04T01:26:45.041] [ERROR] app - 数据传输错误,请联系管理员
[2021-02-04T01:33:45.527] [ERROR] app - 401
[2021-02-04T01:33:50.529] [ERROR] app - 401
[2021-02-04T01:33:50.531] [ERROR] app - 401
[2021-02-04T01:37:07.345] [ERROR] app - 401
[2021-02-04T01:37:36.972] [ERROR] app - 401
[2021-02-04T01:37:41.953] [ERROR] app - 401
[2021-02-04T01:37:41.956] [ERROR] app - 401
[2021-02-04T01:40:05.783] [ERROR] app - 数据传输错误,请联系管理员
[2021-02-04T01:40:14.024] [ERROR] app - 数据传输错误,请联系管理员
[2021-02-04T01:43:10.302] [ERROR] app - 401
[2021-02-04T01:43:10.669] [ERROR] app - 数据传输错误,请联系管理员
[2021-02-04T01:44:14.618] [ERROR] app - 401
[2021-02-04T01:44:14.985] [ERROR] app - 数据传输错误,请联系管理员
[2021-02-04T01:46:20.043] [ERROR] app - 401
[2021-02-04T01:46:20.379] [ERROR] app - 数据传输错误,请联系管理员
